trigger: none

pr: none

parameters:
  - name: goforward
    displayName: Go forward
    type: boolean
    default: false

variables:
  - group: release-qa

# resources:
#   repositories:
#   - repository: pipeline_tools
#     type: git
#     name: CodeBin/pipeline-tools

pool:
  vmImage: ubuntu-latest

# extends:
#   template: pipeline_templates/base_template.yml@pipeline_tools
steps:
  - task: Bash@3
    condition: eq('${{ parameters.goforward }}', 'true')
    displayName: Go forward
    inputs:
      targetType: 'inline'
      script: |
        echo "##vso[task.setvariable variable=step1]true"
  
  - task: Bash@3
    condition: eq('${{ parameters.goforward }}', 'false')
    displayName: Don't go forward
    inputs:
      targetType: 'inline'
      script: |
        echo "##vso[task.setvariable variable=step2]true"

  - task: Bash@3
    condition: eq(variables['step1'], 'true')
    displayName: step1 check
    inputs:
      targetType: 'inline'
      script: |
        echo "ok"

  - task: Bash@3
    condition: succeeded()
    displayName: Only if goforward is true
    inputs:
      targetType: 'inline'
      script: |
        echo "ok"
