trigger: none

pr: none

# parameters:
#   - name: goforward
#     displayName: Go forward
#     type: boolean
#     default: false

variables:
  - group: release-qa

# resources:
#   repositories:
#   - repository: pipeline_tools
#     type: git
#     name: CodeBin/pipeline-tools

pool:
  vmImage: ubuntu-latest

# extends:
#   template: pipeline_templates/base_template.yml@pipeline_tools
steps:
  - task: Bash@3
    displayName: Test script
    inputs:
      targetType: 'inline'
      script: |
        . azurelog.sh
      
        run "ls -lhtr"

        group "Meu grupo"
        echo "HA!"
        endgroup
        
        section "Minha section"